# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        admin:
            id: security.admin_provider
#        juror_admin:
#            id: security.juror_admin_provider
#        juror:
#            id: security.juror_provider

    encoders:
        AppBundle/Repositories/OrmAdministrator: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: ~
            context: work-competition
            pattern: ^/admin
            provider: admin
            form_login:
                login_path: public.admin.login
                check_path: public.admin.login
            logout:
                path: /signout
            access_denied_url: public.admin.login

        main:
            anonymous: ~

    role_hierarchy:
        ROLE_JUROR: [ROLE_USER]
        ROLE_JUROR_ADMIN: [ROLE_JUROR]
        ROLE_ADMIN: [ROLE_JUROR_ADMIN]

    access_control:
        -
            path: ^/admin
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/juror-admin
            roles: ROLE_JUROR_ADMIN
        -
            path: ^/juror-admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/juror-admin
            role: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/juror
            role: ROLE_JUROR
        -
            path: ^/juror/login
            role: IS_AUTHENTICATED_ANONYMOUSLY