# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Models\Administrator: bcrypt
        AppBundle\Models\CampaignAdministrator: bcrypt
        AppBundle\Models\Juror: bcrypt
    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [administrator, campaign_admin, juror]
        administrator:
            id: security.administrator_provider
        campaign_admin:
            id: security.campaign_administrator_provider
        juror:
            id: security.juror_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            pattern: ^/
            provider: chain_provider
            form_login:
                login_path: public.login
                check_path: public.login
                default_target_path: /admin
            logout:
                path: /logout
                target: /
            access_denied_url: public.login

    role_hierarchy:
        ROLE_JUROR: [ROLE_USER]
        ROLE_CAMPAIGN_ADMIN: [ROLE_JUROR]
        ROLE_ADMIN: [ROLE_CAMPAIGN_ADMIN]

    access_control:
        -
            path: ^/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/juror
            roles: ROLE_JUROR
        -
            path: ^/admin
            roles: ROLE_ADMIN
        -
            path: ^/campaign-admin
            roles: ROLE_CAMPAIGN_ADMIN