# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: admin
                        roles: 'ROLE_ADMIN'
                    juror_admin:
                        password: juroradmin
                        roles: 'ROLE_JURORADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            http_basic: ~
            pattern: ^/admin/
            logout:
                path:   /admin/logout
                target: /

        juror_admin:
            http_basic: ~
            pattern: ^/juror-admin/
            logout:
                path:   /juror-admin/logout
                target: /

        main:
            anonymous: ~

    access_control:
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/juror-admin/, roles: ROLE_JURORADMIN }
