# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        administrator:
            id: security.administrator_provider
        campaign_admin:
            id: security.campaign_admin_provider
        juror:
            id: security.juror_provider

    encoders:
        Symfony\Component\Security\Core\User\User: bcrypt
        AppBundle\Models\Administrator: bcrypt
        AppBundle\Models\CampaignAdministrator: bcrypt
        AppBundle\Models\Juror: bcrypt

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            anonymous: ~
            context: work-competition
            pattern: ^/admin
            provider: administrator
            form_login:
                login_path: public.admin.login
                check_path: public.admin.login
            logout:
                path: /admin/logout
            access_denied_url: public.admin.login

        campaign_admin:
            anonymous: ~
            context: work-competition
            pattern: ^/camapaign-admin
            provider: campaign_admin
            form_login:
                login_path: public.campaign_admin.login
                check_path: public.campaign_admin.login
            logout:
                path: /campaign-admin/logout
            access_denied_url: public.campaign_admin.login

        juror:
            anonymous: ~
            context: work-competition
            pattern: ^/juror
            provider: juror
            form_login:
                login_path: public.juror.login
                check_path: public.juror.login
            logout:
                path: /juror/logout
            access_denied_url: public.juror.login

        main:
            anonymous: ~

    role_hierarchy:
        ROLE_JUROR: [ROLE_USER]
        ROLE_CAMPAIGN_ADMIN: [ROLE_JUROR]
        ROLE_ADMIN: [ROLE_CAMPAIGN_ADMIN]

    access_control:
        -
            path: ^/admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/campaign-admin/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY
        -
            path: ^/juror
            roles: ROLE_JUROR
        -
            path: ^/admin
            roles: ROLE_ADMIN
        -
            path: ^/campaign-admin
            roles: ROLE_CAMPAIGN_ADMIN
        -
            path: ^/juror/login
            roles: IS_AUTHENTICATED_ANONYMOUSLY